@startuml
title Diagramme de classes - Matching-Service

class OrderBook {
  -id : Long
  -clientOrderId : String
  -userId : Long
  -symbol : String
  -side : String
  -type : String
  -quantity : Integer
  -price : Double
  -duration : String
  -timestamp : LocalDateTime
  -status : String
  -rejectReason : String
  -quantityRemaining : Integer
  -orderId : Long
}

class ExecutionReport {
  -id : Long
  -orderId : Long
  -fillQuantity : Integer
  -fillPrice : Double
  -fillType : String
  -executionTime : LocalDateTime
  -buyerUserId : Long
  -sellerUserId : Long
  -symbol : String
}

OrderBook "1" -- "*" ExecutionReport
@enduml
