@startuml
title Diagramme de classes - Matching-Service

class OrderBook {
  -id : Long
  -clientOrderId : String
  -userId : Long
  -symbol : String
  -side : String
  -type : String
  -quantity : Integer
  -price : Double
  -duration : String
  -timestamp : LocalDateTime
  -status : String
  -rejectReason : String
  -quantityRemaining : Integer
  -orderId : Long
  -version : Long
}

class ExecutionReport {
  -id : Long
  -orderId : Long
  -fillQuantity : Integer
  -fillPrice : Double
  -fillType : String
  -executionTime : LocalDateTime
  -buyerUserId : Long
  -sellerUserId : Long
  -symbol : String
}

class OutboxEvent {
    -id : Long
    -eventID : UUID
    -eventType : String
    -aggregateId : String
    -payload : String
    -createdAt : Instant
    -processedAt : Instant
    -retryCount : Integer
    -maxRetries : Integer
    -nextRetryAt : Instant
    -errorMessage : String
    +isProcessed() : boolean
    +canRetry() : boolean
    +incrementRetryCount() : void
    +markAsProcessed() : void
    +markAsFailed(errorMessage : String) : void
}

OrderBook "1" -- "*" ExecutionReport
@enduml
