@startmindmap
* Qualité BrokerX
** Sécurité
*** MFA obligatoire
*** KYC obligatoire
*** Chiffrement des données
*** Journalisation des accès
*** Gestion des secrets inter-services
*** Sécurité des communications inter-services
** Performance
*** Traitement des ordres < 250 ms (P95)
*** Débit de 800 ordres/s
*** Scalabilité
** Disponibilité
*** Résilience aux pannes
*** Acceptation des ordres même si un service externe est en panne
*** Tolérance aux pannes inter-services
*** Supervision centralisée (logs, métriques)
*** Disponibilité de 95.5 %
** Maintenabilité
*** Modularité
*** Documentation
*** Ajout facile de nouveaux types d’ordres/services
** Testabilité
*** Couverture de code > 95 % (JaCoCo)
*** Indépendance des services externes (mockable)
** Évolutivité
*** Ajout de fonctionnalités sans impact majeur
*** Préparation à la croissance du nombre d’utilisateurs
** Traçabilité
*** Audit complet des opérations critiques
*** Logs d’audit en base
** Conformité
*** Respect des standards financiers
*** RGPD
@endmindmap
